<?php

namespace AppBundle\Repository;

/**
 * PictureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PictureRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPicturesWithCdName($cdName)
    {
        return $this->createQueryBuilder('p')
            ->leftjoin('p.observation', 'o', 'WITH')
            ->leftJoin('o.taxref', 't', 'WITH')
            ->where('t.cdName = :cdName')
            ->setParameter('cdName', $cdName)
            ->orderBy('p.updatedAt', 'DESC')
            ->getQuery()
            ->getResult()
        ;

    }
}
