<?php

namespace AppBundle\Repository;

/**
 * TaxrefLinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxrefLinkRepository extends \Doctrine\ORM\EntityRepository
{
}
