<?php

namespace AppBundle\Repository;

/**
 * TaxrefRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxrefRepository extends \Doctrine\ORM\EntityRepository
{
    public function getFamilyList()
    {
        return $this->createQueryBuilder('t')
            ->orderBy('t.family', 'ASC')
            ->groupBy('t.family')
            ;
    }
}
