<?php

namespace AppBundle\Repository;

/**
 * TaxrefRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxrefRepository extends \Doctrine\ORM\EntityRepository
{
    public function getFamilyList()
    {
        return $this->createQueryBuilder('t')
            ->orderBy('t.family', 'ASC')
            ->groupBy('t.family')
            ;
    }

    public function getSpeciesWithLbNameLike($val)
    {
        return $this->createQueryBuilder('t')
            ->where('t.lbName LIKE :val')
            ->setParameter('val', '%'.$val.'%')
            ->getQuery()
            ->getResult();
    }

    public function getSpeciesWithVernNameLike($val)
    {
        return $this->createQueryBuilder('t')
            ->where('t.vernacularName LIKE :val')
            ->setParameter('val', '%'.$val.'%')
            ->getQuery()
            ->getResult();
    }
}
