# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.reload_taxref_link:
        class: AppBundle\Utils\ReloadTaxrefLink
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@vich_uploader.templating.helper.uploader_helper"

    app.reload_taxref:
        class: AppBundle\Utils\ReloadTaxref
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@vich_uploader.templating.helper.uploader_helper"

    app.create_map_with_observations:
        class: AppBundle\Utils\CreateMapWithObservations

    app.send_contact_mail:
            class: AppBundle\Utils\SendContactMail
            arguments:
                - "@mailer"
                - "@templating"
                - "%mailer_user%"